CREATE TABLE IF NOT EXISTS REGION (
    ID_REGION BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(255) NOT NULL,
    CAPITALE_REGIONALE VARCHAR(255) NOT NULL,
    SUPERFICIE FLOAT NOT NULL,
    POPULATION INT NOT NULL,
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);