CREATE TABLE IF NOT EXISTS APPELER (
    ID_APPELER BIGINT PRIMARY KEY AUTO_INCREMENT,
    DATE_SERVICE DATE NOT NULL,
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    
    ID_MUNICIPAL BIGINT,
    FOREIGN KEY (ID_MUNICIPAL) REFERENCES MUNICIPAL(ID_MUNICIPAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    ID_TECHNICIEN BIGINT,
    FOREIGN KEY (ID_TECHNICIEN) REFERENCES TECHNICIEN(ID_TECHNICIEN)
        ON DELETE CASCADE
        ON UPDATE CASCADE    
);
