CREATE TABLE IF NOT EXISTS ADMINISTRATEUR (
    ID_ADMIN BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(255) NOT NULL,
    PRENOM VARCHAR(255) NOT NULL,
    NOM_UTILISATEUR VARCHAR(255) NOT NULL,
    TELEPHONE VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    EMAIL_AUTH VARCHAR(255) UNIQUE NOT NULL,
    MOT_DE_PASSE VARCHAR(255) NOT NULL,
    CIN VARCHAR(20) NOT NULL,
    DATE_NAISSANCE DATE NOT NULL,
    LIEU_NAISSANCE VARCHAR(255) NOT NULL,
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
